# Generated by Django 5.2.6 on 2025-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlmm_app', '0005_auto_20250914_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_revenue',
            field=models.BooleanField(default=False),
        ),
    ]
